### ISSUE TITLE
Download (json) ignores painted elements; Upload (json) ignores material 

### ISSUE THREAD

**Issue by Wizeowel** [Sinetheta/blueprintnotincluded#2]
I made this
![test1_elements](https://user-images.githubusercontent.com/44842348/224001507-8f6a741b-ada9-436e-85d9-74cac7e0472c.png)

When downloading json I see only 5 buildingdefs: the tiles only; not the water
[test1.blueprint.txt](https://github.com/Sinetheta/blueprintnotincluded/files/10930585/test1.blueprint.txt)

When uploading json I see 5 sandstone tiles instead of the various materials I had chosen before.

**Comment by Wizeowel** [comment]
Could be that the json is meant for interoperability with blueprints mod, and not so much for making personal backups.

**Comment by RaceFPV** [comment]
Thats correct, the json is meant to be compatible with blueprints, so we can't store water data as blueprints doesnt know what to do with water tiles.
