### ISSUE TITLE
Get shareable URL

### ISSUE THREAD

**Issue by Wizeowel** [Sinetheta/blueprintnotincluded#3]
Get shareable URL links to old site, e.g.

https://blueprintnotincluded.com/b/64062d89353cbe88129a607e

**Comment by Sinetheta** [comment]
Resolved by https://github.com/Sinetheta/blueprintnotincluded/commit/5bc3992bc0e3f6a0f55c24a67d1722f4d1c79cd5

and changing the static site's `catchall_document` to `index.html`

https://blueprintnotincluded.org/b/64086242353cbe36b29a6081
